# Generated by Django 5.1.3 on 2024-12-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='C:\\Users\\Vlad\\Desktop\\django_apps\\social_media\\media\\blank-profile-picture-973460_1280.png', upload_to='profile_images'),
        ),
    ]
