# Generated by Django 5.1.3 on 2024-12-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ceated_at',
            new_name='created_at',
        ),
    ]
